== Local development

=== Prerequisites:

- Docker
- https://k3d.io/[k3d]
- https://helm.sh/docs/intro/install/[Helm]
- NodeJs

=== Create k3d cluster

`k3d cluster create mycluster --config k3d-config.yaml --servers-memory 6GB`

This command will create simple k3d cluster with one node, exposing several ports

=== Synthesize https://cdk8s.io/docs/latest/[cdk8s] scripts

- Navigate inside /kube folder
- Run `npm install` (only the first time)
- Run `npm run import` (only the first time)
- Run `npm watch` (to continuously watch for changes)
- Run `npm synth` (after every change)

This will create all k8s yaml files inside dist directory.

=== Run startup script:

First time you run this, in fresh helm installation, you must first add repos:
`helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`
`helm repo add strimzi https://strimzi.io/charts/`
And update them:
`helm repo update`

Now you can run the script:

`/kube/start.sh`

This script will:

- install Prometheus/Grafana using Helm https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack[kube-prometheus-stack]

- install https://strimzi.io/[strimzi-operator] using Helm for managed kafka components

- install default Strimzi Pod Monitors using link:obs/strimzi-pod-monitor.yaml[/obs/strimzi-pod-monitor.yaml]

- Apply all cdk8s generated scripts, installing all storage related components as well as kafka, kafka-connect, tempo, loki, kafka-ui, and a postgres database used by senik app.

NOTE: cdk8s script are separated between main.ts and storageClass.ts.
The storageClass file creates the storage class used in k3d to retain volumes between restarts as well as all PVCs needed for pods to actually retain data between pod deletions.

NOTE: When making changes to cdk8s scripts (and thus to k8s yaml files) running:
`kubectl apply -f dist/0001-snk` should usually be enough, unless you make changes to PVCs then you have to also run: `kubectl apply -f dist/0000-snk-storage`.

CAUTION: if you want to delete all the pods please use `kubectl delete -f dist/0001-snk` so that PVCs are not deleted, and no data loss occurs!


