server:
  http_listen_port: 3200

distributor:
  receivers:
    zipkin:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

overrides:
  metrics_generator_processors: [ service-graphs, span-metrics ] # enables metrics generator
